FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y texlive-latex-recommended
RUN apt update && apt install -y \
        texlive-lang-german\
        texlive-latex-extra\
        texlive-science\
        texlive-bibtex-extra\
        texlive-luatex\
        biber
RUN apt-get update && apt-get install -y \
        latexmk\
        fonts-cmu
RUN apt-get update && apt-get install -y \
        python-pygments \
        python3-pygments
RUN apt update && apt install -y git make

ENTRYPOINT /bin/bash
